version: '3.8'
services:
    php-apache:
        container_name: vsnippet-pathTraversal-improper-regex-18
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
