version: '3.8'
services:
    php-apache:
        container_name: vsnippet-pathTraversal-replace-limit-26
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
